### PR TITLE
antimev: fix preblock dkg index and update generation test

### LINKED ISSUE #406: Privnet breakdown with `TestGenerateEncryptedTx` output
#### System information

Geth version: `0.3.0-unstable`
OS & Version: Linux
Commit hash : [be5f081](https://github.com/bane-labs/go-ethereum/commit/be5f081ee4e1cd3c45768bc8f57b5ca27eb60af4)

#### Expected behaviour

Privnet was able to decrypt transactions generated by `TestGenerateEncryptedTx`.

#### Actual behaviour

Privnet now breaks down after receive the transaction and is able to recover.

#### Steps to reproduce the behaviour

1. Set up a privnet with `make privnet_start_seven`;
2. Run `TestGenerateEncryptedTx` after Height 30;
3. Send an envelope transaction after Height 35, ref https://github.com/bane-labs/go-ethereum/tree/be5f081ee4e1cd3c45768bc8f57b5ca27eb60af4/privnet#commands-in-javascript-console.

#### Backtrace

The generation test now gives envelope data like following.

```
=== RUN   TestGenerateEncryptedTx
    tpke_test.go:162: encryptedKey: 8e2ed43e73a361ac579b59fe9c1b863a6f87376912fc99959bf0aaa452da7a0cc38bdbee6f460b75559ca5b25310eb5b956755f47f7631d8cd63cbc95fc6893a860770e126cfea386a0d6a4392ad0adc73297e44192a2bb7895b44580f855a339810aca1321c559ca93d342f3bb11dc3057bf6b7a3b678dabfb0f384c6f19e545421844b29c63ae008693960282581bc1283fccdbe9d4bb8ad99b6f4748dd1f2db6abc294f37aaf8253daa37981bf55f5b6bbcee734ce95004e5d04bdc6957a1
        encryptedMsg: b1d36193698c25d364b7fe8d0a8da55dca630b5a764216e8699e5e33f1c3d4bb4b391a1b71a1ff3029f97de7b17d470736d1d1ced9439b0a2dc4e14cea171ab9363735fe5b1e915018baed5f2ba6eea545a364678abd8f2457e984d607f03565b39e53671d8acdf99111ad83a68f472e
        envelopeData: 0xffffffff010000008e2ed43e73a361ac579b59fe9c1b863a6f87376912fc99959bf0aaa452da7a0cc38bdbee6f460b75559ca5b25310eb5b956755f47f7631d8cd63cbc95fc6893a860770e126cfea386a0d6a4392ad0adc73297e44192a2bb7895b44580f855a339810aca1321c559ca93d342f3bb11dc3057bf6b7a3b678dabfb0f384c6f19e545421844b29c63ae008693960282581bc1283fccdbe9d4bb8ad99b6f4748dd1f2db6abc294f37aaf8253daa37981bf55f5b6bbcee734ce95004e5d04bdc6957a1b1d36193698c25d364b7fe8d0a8da55dca630b5a764216e8699e5e33f1c3d4bb4b391a1b71a1ff3029f97de7b17d470736d1d1ced9439b0a2dc4e14cea171ab9363735fe5b1e915018baed5f2ba6eea545a364678abd8f2457e984d607f03565b39e53671d8acdf99111ad83a68f472e
        encrypted tx hash: 0xb7bad8db22ff3f7d1fcd09b9b620f9b0d43c92a18f00be2d639e3f107fda2dec
```

And the privnet will break down with following messages.

```
INFO [02-05|16:09:53.464] Commit new sealing work                  number=37 sealhash=9b87db..b54649 "parent hash"=6ee8fa..2f490b etherbase=0x1212000000000000000000000000000000000003 txs=1 gas=31094      fees=0.00062188 elapsed=154.205ms
INFO [02-05|16:09:53.502] New block in the chain                   "dbft index"=36 "chain index"=36 hash=0x6ee8fa60329d0e6fd6a050208232e99ae2c0fb4200cb416ad9e611f5c42f490b "parent hash"=0x92a0191ad0b386dcbcab4de07f9d08d99859639c591880cb3cec2113bb238dad primary=1 coinbase=0x1212000000000000000000000000000000000003 "mix digest"=0xbc41f4e044fc90ae5d6178f3f7570ae44c17a7aa86828557389d4f404d61b192
INFO [02-05|16:09:53.502] Fetching latest sealing proposal         "desired number"=37
INFO [02-05|16:09:53.694] Sealing proposal updated                 number=37 sealhash=9b87db..b54649 "parent hash"=6ee8fa..2f490b txs=1
2025-02-05T16:09:53.695+0800	INFO	dbft@v0.3.2/dbft.go:112	initializing dbft	{"height": 37, "view": 0, "index": 2, "role": "Primary"}
2025-02-05T16:09:53.696+0800	DEBUG	dbft@v0.3.2/dbft.go:712	reset timer	{"h": 37, "v": 0, "delay": "8.581846727s"}
2025-02-05T16:09:53.696+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 6, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.696+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.697+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 1, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.697+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.697+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 3, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.697+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.697+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 4, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.697+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.699+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 4, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.702+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.702+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 1, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.703+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.703+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 3, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.703+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.703+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 0, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.704+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.705+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 3, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.706+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.707+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 1, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.707+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.707+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 5, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.708+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.708+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 3, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.708+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.708+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 4, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.708+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.708+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 6, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.709+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.710+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 4, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.711+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.712+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 0, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.712+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.712+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 3, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.713+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.713+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 5, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.715+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.715+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 0, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.715+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.715+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 5, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.716+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.716+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 5, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.717+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.717+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 3, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.717+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.717+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 6, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.717+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.718+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 0, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.718+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.718+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 5, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.718+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.718+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 6, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.718+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:09:53.719+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "Commit", "from": 5, "height": 36, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:09:53.719+0800	DEBUG	dbft@v0.3.2/dbft.go:241	ignoring old height	{"height": 36}
2025-02-05T16:10:02.279+0800	DEBUG	dbft@v0.3.2/dbft.go:203	timeout	{"height": 37, "view": 0}
2025-02-05T16:10:02.292+0800	DEBUG	dbft@v0.3.2/send.go:10	broadcasting message	{"type": "PrepareRequest", "height": 37, "view": 0}
2025-02-05T16:10:02.295+0800	INFO	dbft@v0.3.2/send.go:39	sending PrepareRequest	{"height": 37, "view": 0}
2025-02-05T16:10:02.295+0800	DEBUG	dbft@v0.3.2/dbft.go:712	reset timer	{"h": 37, "v": 0, "delay": "10s"}
2025-02-05T16:10:02.296+0800	DEBUG	dbft@v0.3.2/check.go:35	check preparations	{"hasReq": true, "count": 1, "M": 5}
2025-02-05T16:10:02.418+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PrepareResponse", "from": 5, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.419+0800	INFO	dbft@v0.3.2/dbft.go:465	received PrepareResponse	{"validator": 5}
2025-02-05T16:10:02.419+0800	DEBUG	dbft@v0.3.2/check.go:35	check preparations	{"hasReq": true, "count": 2, "M": 5}
2025-02-05T16:10:02.503+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PrepareResponse", "from": 5, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.503+0800	DEBUG	dbft@v0.3.2/dbft.go:453	ignoring PrepareResponse	{"dup": true, "sor": true, "viewChanging": false, "moreThanF": true}
2025-02-05T16:10:02.504+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PrepareResponse", "from": 6, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.504+0800	INFO	dbft@v0.3.2/dbft.go:465	received PrepareResponse	{"validator": 6}
2025-02-05T16:10:02.504+0800	DEBUG	dbft@v0.3.2/check.go:35	check preparations	{"hasReq": true, "count": 3, "M": 5}
2025-02-05T16:10:02.504+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PrepareResponse", "from": 3, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.505+0800	INFO	dbft@v0.3.2/dbft.go:465	received PrepareResponse	{"validator": 3}
2025-02-05T16:10:02.505+0800	DEBUG	dbft@v0.3.2/check.go:35	check preparations	{"hasReq": true, "count": 4, "M": 5}
2025-02-05T16:10:02.505+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PrepareResponse", "from": 5, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.505+0800	DEBUG	dbft@v0.3.2/dbft.go:453	ignoring PrepareResponse	{"dup": true, "sor": true, "viewChanging": false, "moreThanF": true}
2025-02-05T16:10:02.541+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PrepareResponse", "from": 6, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.541+0800	DEBUG	dbft@v0.3.2/dbft.go:453	ignoring PrepareResponse	{"dup": true, "sor": true, "viewChanging": false, "moreThanF": true}
2025-02-05T16:10:02.588+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PrepareResponse", "from": 0, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.588+0800	INFO	dbft@v0.3.2/dbft.go:465	received PrepareResponse	{"validator": 0}
2025-02-05T16:10:02.588+0800	DEBUG	dbft@v0.3.2/check.go:35	check preparations	{"hasReq": true, "count": 5, "M": 5}
2025-02-05T16:10:02.622+0800	INFO	dbft@v0.3.2/send.go:155	sending PreCommit	{"height": 37, "view": 0}
2025-02-05T16:10:02.623+0800	DEBUG	dbft@v0.3.2/send.go:10	broadcasting message	{"type": "PreCommit", "height": 37, "view": 0}
2025-02-05T16:10:02.664+0800	DEBUG	dbft@v0.3.2/dbft.go:712	reset timer	{"h": 37, "v": 0, "delay": "10s"}
2025-02-05T16:10:02.664+0800	DEBUG	dbft@v0.3.2/check.go:66	not enough PreCommits to process PreBlock	{"count": 1}
2025-02-05T16:10:02.738+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PrepareResponse", "from": 4, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.738+0800	INFO	dbft@v0.3.2/dbft.go:465	received PrepareResponse	{"validator": 4}
2025-02-05T16:10:02.738+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PrepareResponse", "from": 0, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.739+0800	DEBUG	dbft@v0.3.2/dbft.go:453	ignoring PrepareResponse	{"dup": true, "sor": true, "viewChanging": false, "moreThanF": false}
2025-02-05T16:10:02.739+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PrepareResponse", "from": 4, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.739+0800	DEBUG	dbft@v0.3.2/dbft.go:453	ignoring PrepareResponse	{"dup": true, "sor": true, "viewChanging": false, "moreThanF": false}
2025-02-05T16:10:02.739+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 0, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.757+0800	INFO	dbft@v0.3.2/dbft.go:550	received PreCommit	{"validator": 0}
ERROR[02-05|16:10:02.757] some decryption shares are missing       validator=0x0B51369D02e47EE3f143391B837Aa08c31AAA19b expected=1 "got for current round"=0 "got for previous round"=0
2025-02-05T16:10:02.757+0800	DEBUG	dbft@v0.3.2/check.go:66	not enough PreCommits to process PreBlock	{"count": 2}
2025-02-05T16:10:02.757+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 6, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.758+0800	INFO	dbft@v0.3.2/dbft.go:550	received PreCommit	{"validator": 6}
ERROR[02-05|16:10:02.758] some decryption shares are missing       validator=0xfEf5F250aF14DF73f983cAAb7b1F5002189c42E0 expected=1 "got for current round"=0 "got for previous round"=0
2025-02-05T16:10:02.758+0800	DEBUG	dbft@v0.3.2/check.go:66	not enough PreCommits to process PreBlock	{"count": 3}
2025-02-05T16:10:02.758+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PrepareResponse", "from": 4, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.758+0800	DEBUG	dbft@v0.3.2/dbft.go:453	ignoring PrepareResponse	{"dup": true, "sor": true, "viewChanging": false, "moreThanF": true}
2025-02-05T16:10:02.759+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PrepareResponse", "from": 0, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.759+0800	DEBUG	dbft@v0.3.2/dbft.go:453	ignoring PrepareResponse	{"dup": true, "sor": true, "viewChanging": false, "moreThanF": true}
2025-02-05T16:10:02.759+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PrepareResponse", "from": 4, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.759+0800	DEBUG	dbft@v0.3.2/dbft.go:453	ignoring PrepareResponse	{"dup": true, "sor": true, "viewChanging": false, "moreThanF": true}
2025-02-05T16:10:02.759+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 6, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.760+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PrepareResponse", "from": 4, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.760+0800	DEBUG	dbft@v0.3.2/dbft.go:453	ignoring PrepareResponse	{"dup": true, "sor": true, "viewChanging": false, "moreThanF": true}
2025-02-05T16:10:02.760+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PrepareResponse", "from": 4, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.760+0800	DEBUG	dbft@v0.3.2/dbft.go:453	ignoring PrepareResponse	{"dup": true, "sor": true, "viewChanging": false, "moreThanF": true}
2025-02-05T16:10:02.760+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 3, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.760+0800	INFO	dbft@v0.3.2/dbft.go:550	received PreCommit	{"validator": 3}
ERROR[02-05|16:10:02.792] some decryption shares are missing       validator=0x910AD1641B7125Eff746acCdCa1F11148b22f472 expected=1 "got for current round"=0 "got for previous round"=0
2025-02-05T16:10:02.793+0800	DEBUG	dbft@v0.3.2/check.go:66	not enough PreCommits to process PreBlock	{"count": 4}
2025-02-05T16:10:02.793+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PrepareResponse", "from": 1, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.793+0800	INFO	dbft@v0.3.2/dbft.go:465	received PrepareResponse	{"validator": 1}
2025-02-05T16:10:02.793+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 0, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.793+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 6, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.794+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 5, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.794+0800	INFO	dbft@v0.3.2/dbft.go:550	received PreCommit	{"validator": 5}
ERROR[02-05|16:10:02.794] some decryption shares are missing       validator=0xC5bbD9652546BC96bE3DEc97a38eE335f7873Dfa expected=1 "got for current round"=0 "got for previous round"=0
2025-02-05T16:10:02.794+0800	INFO	dbft@v0.3.2/check.go:73	processing PreBlock	{"height": 37, "view": 0, "tx_count": 1, "preCommit_count": 5}
ERROR[02-05|16:10:02.795] number of shares for the previous round mismatch round=1 validator=0 "validator DKG index"=7 expected=1 actual=0
ERROR[02-05|16:10:02.795] number of shares for the previous round mismatch round=1 validator=2 "validator DKG index"=1 expected=1 actual=0
ERROR[02-05|16:10:02.795] number of shares for the previous round mismatch round=1 validator=3 "validator DKG index"=2 expected=1 actual=0
ERROR[02-05|16:10:02.795] number of shares for the previous round mismatch round=1 validator=5 "validator DKG index"=5 expected=1 actual=0
ERROR[02-05|16:10:02.795] number of shares for the previous round mismatch round=1 validator=6 "validator DKG index"=3 expected=1 actual=0
2025-02-05T16:10:02.874+0800	INFO	dbft@v0.3.2/check.go:81	can't process PreBlock, waiting for more PreCommits to be collected	{"error": "invalid number of Decrypted transactions: expected 1, actual 0", "count": 5}
2025-02-05T16:10:02.907+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 5, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.907+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 4, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.907+0800	INFO	dbft@v0.3.2/dbft.go:550	received PreCommit	{"validator": 4}
ERROR[02-05|16:10:02.907] some decryption shares are missing       validator=0xc51964013acbC6b271FEeCB0feBD9E7A01202930 expected=1 "got for current round"=0 "got for previous round"=0
2025-02-05T16:10:02.908+0800	INFO	dbft@v0.3.2/check.go:73	processing PreBlock	{"height": 37, "view": 0, "tx_count": 1, "preCommit_count": 6}
ERROR[02-05|16:10:02.908] number of shares for the previous round mismatch round=1 validator=0 "validator DKG index"=7 expected=1 actual=0
ERROR[02-05|16:10:02.908] number of shares for the previous round mismatch round=1 validator=2 "validator DKG index"=1 expected=1 actual=0
ERROR[02-05|16:10:02.908] number of shares for the previous round mismatch round=1 validator=3 "validator DKG index"=2 expected=1 actual=0
ERROR[02-05|16:10:02.908] number of shares for the previous round mismatch round=1 validator=4 "validator DKG index"=4 expected=1 actual=0
ERROR[02-05|16:10:02.909] number of shares for the previous round mismatch round=1 validator=5 "validator DKG index"=5 expected=1 actual=0
ERROR[02-05|16:10:02.909] number of shares for the previous round mismatch round=1 validator=6 "validator DKG index"=3 expected=1 actual=0
2025-02-05T16:10:02.915+0800	INFO	dbft@v0.3.2/check.go:81	can't process PreBlock, waiting for more PreCommits to be collected	{"error": "invalid number of Decrypted transactions: expected 1, actual 0", "count": 6}
2025-02-05T16:10:02.915+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 3, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.916+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 5, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.916+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PrepareResponse", "from": 4, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.916+0800	DEBUG	dbft@v0.3.2/dbft.go:453	ignoring PrepareResponse	{"dup": true, "sor": true, "viewChanging": false, "moreThanF": true}
2025-02-05T16:10:02.916+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 6, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.916+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 6, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.917+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 4, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.958+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 4, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.958+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 1, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:02.958+0800	INFO	dbft@v0.3.2/dbft.go:550	received PreCommit	{"validator": 1}
ERROR[02-05|16:10:02.959] some decryption shares are missing       validator=0x26F1794B81dF2B832545b8B6bbcA196b82E4fEB1 expected=1 "got for current round"=0 "got for previous round"=0
2025-02-05T16:10:02.959+0800	INFO	dbft@v0.3.2/check.go:73	processing PreBlock	{"height": 37, "view": 0, "tx_count": 1, "preCommit_count": 7}
ERROR[02-05|16:10:02.959] number of shares for the previous round mismatch round=1 validator=0 "validator DKG index"=7 expected=1 actual=0
ERROR[02-05|16:10:02.959] number of shares for the previous round mismatch round=1 validator=1 "validator DKG index"=6 expected=1 actual=0
ERROR[02-05|16:10:02.959] number of shares for the previous round mismatch round=1 validator=2 "validator DKG index"=1 expected=1 actual=0
ERROR[02-05|16:10:02.960] number of shares for the previous round mismatch round=1 validator=3 "validator DKG index"=2 expected=1 actual=0
ERROR[02-05|16:10:02.960] number of shares for the previous round mismatch round=1 validator=4 "validator DKG index"=4 expected=1 actual=0
ERROR[02-05|16:10:02.960] number of shares for the previous round mismatch round=1 validator=5 "validator DKG index"=5 expected=1 actual=0
ERROR[02-05|16:10:02.960] number of shares for the previous round mismatch round=1 validator=6 "validator DKG index"=3 expected=1 actual=0
2025-02-05T16:10:03.006+0800	INFO	dbft@v0.3.2/check.go:81	can't process PreBlock, waiting for more PreCommits to be collected	{"error": "invalid number of Decrypted transactions: expected 1, actual 0", "count": 7}
2025-02-05T16:10:03.006+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 1, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:03.007+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 5, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:03.007+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 1, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:03.007+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 1, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:03.007+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 1, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:12.642+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "RecoveryMessage", "from": 6, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:12.642+0800	DEBUG	dbft@v0.3.2/dbft.go:646	recovery message received	{"dump": {"ValidBlockStart":0,"ValidBlockEnd":37,"Sender":"0xfef5f250af14df73f983caab7b1f5002189c42e0","Data":"+QeOQSUGgPkHh/kB6vhEgLhB8cGSz0bnsA8cOdlB/qYOi7/aKTjpujusy/pptOlr45U7YxdNgKU7xQQM9RTmskIdEmhnZgk2lAflQ/VF4q6UawD4RAG4QbvqHM7/fUnR0sTPa+sUoairBfa7vj9CeTpze1R5sNFffJQo7oUA3EzcODZ7snAbI2LQpqrAdiYBGlSd/C8aNgsB+EQCuEGjVDOHKdtj4QaXVfyT91MhKSGou1YORoT0ORzR4diAKgHeBB30VfnFFOglmnZKa7ojLqv5ixcoBMxwmxyFwiFoAfhEA7hBX4Lx5CnNKV7K+MogkW2jZhSZ1+jWt3SrWE9I6QuX5456W7QfQ7Ju7jkrHZTob7FklxbXx6AjduF7IMnCg/V3IAD4RAS4QUpHpUkfswcIhii8wVMvHjT24J8gRRz1lbSI8ez+yWvTMjtt0mxJuF2l5MeSbPfWi7lxMByLMFYJHP5bN7lo+4EA+EQFuEErBfkBd9/4AIWRIS18FijTqhpul4btV/48BNMdEusLUEMxeGnxfW4PBz9PKs79KZUPw3UM0/6vxiOW1Y16gNYYAPhEBrhBLOgM0a8R1j/NZS13gUznNT8XCfV/WiEqLhbJWXTs0JlMI07MZhqh6nyqf6aFt2L0utembDN3OM1EyN+pSuBoLgD5AjD4ToCAiAAAAAAAAAAAuEGihatB2OD15erCqg9t14Vv0qAlM2zdf5mLgJHY4/OzukZj9jouIe67ULsNiJkaQzcKHsvUSicAhS9x5lhngXx9AfhOgAGIAAAAAAAAAAC4QbCfTj5/LDrw5Y8E3QfwPX+1k2MbIn4gyaL0yJ83+BfGPzU9gK2fWxxWum1A1Xymn7AxbWuKaOyvmxhcv3Lso0sB+E6AAogAAAAAAAAAALhB4qynO/fPxhlaxVfP6KX+MZ9FifRt3in1ZZssTkTCU5ooNTg+jIP5lB/oIVMmR1mxqeXHfGHRkN9yKgIpksbaPAD4ToADiAAAAAAAAAAAuEHCWyQrV/TEgqg0WyeRth3qKnkKuXbC6+C13KP00UVJSkDMH84bHYw99EItDK1cWQiA+uqV6wYoRZ7yc59idzmcAfhOgASIAAAAAAAAAAC4QahmlrVG3x02C3L/BgnMTbm+y2CuixMSEX0y6//5qDD7L6n99ae515Aeqf2ANikaNczNaXpgju0wmfbQRZYKMMEB+E6ABYgAAAAAAAAAALhBm9EQdmDHtHHmWbXGh93ZYZtFFHMIm7DfK1kCWsuGCZJjU187ihvQbN73O8Ynm5nOucpVm143GxA/cdfQbx4RUwH4ToAGiAAAAAAAAAAAuEGZ3vT+0FlsENwo6VEqzleW61g5tPo1gRhoxFYvxkCvkimaremeEUsj5qCreofZH7MRXhBfC9X2I7Xke+v6QnwvAcDAoOpHrUVkJsuLfylEPxPt+1mBwB9IeiLEYdaBVmbI+06o+QNBIICAgPkDOvkCQKBu6PpgMp0Ob9agUCCCMuma4sD7QgDLQWrZ5hH1xC9JC6AdzE3o3sddequFtWe2zNQa0xJFG5SKdBPwoUL9QNSTR5QSEgAAAAAAAAAAAAAAAAAAAAAAA6DcPMf/QsgZELqd4795MQC2o4pIIkVA21+EQuI6M2hz8qDYJlJ9gX7xrkpGII1SZ7iYLIdsLn2Qtd1NXyVKbnCUyKCzcLCUhEgnv3/Jl0zsGW/vwfZDRzNKcVIHpU6PHWzi17kBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACJYQBycOAgnl2hGejHNGiAQE+SLyPLrUCJnsermve0uzjGimCnN+Ur7RPN2iHAmQ+Q6C8QfTgRPyQrl1hePP3VwrkTBenqoaChVc4nU9ATWGxkogAAAAAAAAAAoUEqBfIAKBW6B8XG8xVpv+DReaSwPhuW0jgG5lsrcABYi+142O0IeGgzegbbXCveg/3xuXhnPkOeBg0t43uo0frmIinoYHyNR6gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC4sgEBPki8jy61AiZ7Hq5r3tLs4xopgpzflK+0TzdohwJkPkOJAdP2hpEiAJsplMGc4pC1RyazCnSPEI3oUOso5hSjZtTYTVkg7c/OhB/XSIEFMZ2s7cngpI2n0PnD7aTOpPPG5fEm4eFmr4j0POCQ6ZkTcNUVuQgUlxTXtjpLpE45dWYRnUEWvNziSQ8Ayits/xiTZa7/WKI2q+Ge3udV56uWc7NTmTA0JWAWojYKSIk3+hA=","Witness":"toBO5l9cncdphpWH1PL9XqbbYJK9phyvrjm4V36RPEwEY27y0pdbXVsmbTPOc9TfhQtAGTTJWvDNYuNpz3dFuAE=","Type":65,"BlockIndex":37,"ValidatorIndex":6,"ViewNumber":0}}
2025-02-05T16:10:12.659+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 0, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:12.659+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 1, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:12.659+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 2, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:12.660+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 3, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:12.660+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 4, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:12.660+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 5, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:12.660+0800	DEBUG	dbft@v0.3.2/dbft.go:232	received message{"type": "PreCommit", "from": 6, "height": 37, "view": 0, "my_height": 37, "my_view": 0}
2025-02-05T16:10:12.661+0800	DEBUG	dbft@v0.3.2/dbft.go:660	recovering finished cv=0/7 preq=0/0 presp=0/7 pco=7/7 co=0/7

```

@AnnaShaleva May relate to #396.

### PR DESCRIPTION
**Pull request by txhsl**
Close #406. @songb2 Please test the features introduced by #396.

### CODE REVIEW

File: antimev/tpke_test.go [hunk 1]
```diff
@@ -176,12 +176,12 @@ func TestGenerateEncryptedTx(t *testing.T) {
...
 }
 
-// buildTransferFromPriv1 returns a signed transaction that transfers 1 wei from
-// node1 to node1 with nonce 0.
-func buildTransferFromPriv1(t *testing.T) *types.Transaction {
-	ks := keystore.NewKeyStore(filepath.Join("..", "privnet", "seven", "node1", "keystore"), keystore.StandardScryptN, keystore.StandardScryptP)
+// buildTransferFromPriv0 returns a signed transaction that transfers 1 wei from
+// node0 to node0 with nonce 0.
+func buildTransferFromPriv0(t *testing.T) *types.Transaction {
+	ks := keystore.NewKeyStore(filepath.Join("..", "privnet", "seven", "node0", "keystore"), keystore.StandardScryptN, keystore.StandardScryptP)
```
Comment (roman-khimov) [inline antimev/tpke_test.go:182]: Not sure what this change buys you.

File: consensus/dbft/dbft.go [hunk 2]
```diff
@@ -1260,7 +1260,7 @@ func (c *DBFT) newPreBlockFromContext(sealingProposal *types.Header) *PreBlock {
 	// called by dBFT library to properly initialize PreBlock's transactions.
 	res := &PreBlock{
 		header:                 h,
-		dkgRound:               uint32(c.dkgSnapshot.Round),
+		dkgRound:               uint32(c.dkgSnapshot.Round - 1),
```
Comment (roman-khimov) [inline consensus/dbft/dbft.go:1263]: But this one seems to be correct.

File: antimev/tpke_test.go (hunk 1 above)
Comment (txhsl) [reply antimev/tpke_test.go:182]: The reason is that node0 is watch-only, so its `nonce` starts from `0`. But with a dynamic DKG, CN1/Node1 sends transactions regularly, so the following construction might be invalid.

https://github.com/bane-labs/go-ethereum/blob/be5f081ee4e1cd3c45768bc8f57b5ca27eb60af4/antimev/tpke_test.go#L189-L204

Comment (roman-khimov) [reply antimev/tpke_test.go:182]: It'd be nice to have this explanation in the commit message.

**Review by roman-khimov — APPROVED** [review]

File: consensus/dbft/dbft.go (hunk 2 above)
Comment (AnnaShaleva) [inline consensus/dbft/dbft.go:1263]: To be honest, I still have doubts about semantic of `c.dkgSnapshot.Round` value. In the first version of https://github.com/bane-labs/go-ethereum/pull/396 I used `c.dkgSnapshot.Round - 1` value because from the comments it's clear that `c.dkgSnapshot.Round` always points to the next round. But then I reverted to `c.dkgSnapshot.Round` because round value stored in the KeyManagement contract starts with `1` (and it's definitely the number of the current round, not the next one).

@txhsl, are you sure we need this change? What is the index of the first DKG round from the end-user's PoW, is it `0` or `1`?

Comment (txhsl) [reply consensus/dbft/dbft.go:1263]: The round number in contract is the number of successful DKG rounds, suppose it's `n`. Then the `c.dkgSnapshot.Round` is the current ongoing DKG round number, then it is `n+1`.

For our users, they can only access the contract number, which is the DKG round that the BLS and TPKE are currently using. `c.dkgSnapshot.Round` is only used to handle DKG, not things after.

> @txhsl, are you sure we need this change?

This PR can be verified through testing, or we can use `uint32(c.amevKeystore.Round())` here, maybe it seems more correct to you.

>  What is the index of the first DKG round from the end-user's PoW, is it `0` or `1`?

It's `1`.

Comment (AnnaShaleva) [reply consensus/dbft/dbft.go:1263]: Good, no changes required.

> or we can use uint32(c.amevKeystore.Round()) here

I’d prefer to rely on snapshot here, because it’s always synchronised with dBFT state and can’t be accessed by other threads.
