### PR TITLE
dbft: support disabled NeoXAMEV fork

### LINKED ISSUE #370: Can not run a member node without `neoXAMEVBlock`
#### System information

OS & Version: Linux
Commit hash : [4c9105e](https://github.com/bane-labs/go-ethereum/commit/4c9105ea2bc246729db0540fce2df02074e21087)

#### Expected behaviour

Ref https://github.com/bane-labs/go-ethereum/pull/332#discussion_r1873670877, we expect to first enable only `NeoXDKG` (and keep `NeoXAMEV` disabled). So in the genesis file, we need to set `neoXAMEVBlock` to `nil` while give `neoXDKGBlock` a value.

#### Actual behaviour

However, without `neoXAMEVBlock`, we will get an error when creating the dBFT engine. About the reason, maybe ref https://github.com/bane-labs/go-ethereum/pull/332#discussion_r1889841515 and https://github.com/nspcc-dev/dbft/blob/be64b5f47672278bf4763d1eeb1e34cb2e7ad71f/config.go#L167.

#### Steps to reproduce the behaviour

Delete the `neoXAMEVBlock` field of the PrivNet genesis file and start up a local network.

#### Backtrace

````
INFO [12-20|18:40:50.355] State scheme set to already existing     scheme=hash
Fatal: Failed to register the Ethereum service: failed to create dBFT engine: failed to initialize dBFT: invalid config: NewPreBlockFromContext is set, but AntiMEVExtensionEnablingHeight is not specified
````

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Close #370 and prettify dBFT callbacks along the way.

### CODE REVIEW

**Comment by roman-khimov** [comment]
Conflicts.

**Comment by AnnaShaleva** [comment]
Ready for review.

File: consensus/dbft/dbft.go [hunk 1]
```diff
@@ -283,759 +283,831 @@ func New(chainCfg *params.ChainConfig, _ ethdb.Database) (*DBFT, error) {
...
-			return res
-		}),
-		dbft.WithRequestTx[common.Hash](func(hashes ...common.Hash) {
-			if len(hashes) == 0 {
-				return
+	// Avoid copying and may safely change the block itself, as this part
+	// of code is guaranteed to be called once by dBFT.
+	var pub *tpke.PublicKey
+	if c.chain.Config().IsNeoXAMEV(dbftBlock.header.Number) {
+		pub, _ = c.amevKeystore.GlobalPublicKey()
```
Comment (roman-khimov) [inline consensus/dbft/dbft.go]: There was a lock here.

**Review by roman-khimov — APPROVED** [review]
