### PR TITLE
consensus/dbft: fix DKG data synchronization under discontinuous mining flow

### LINKED ISSUE #474: DKG synchronization inside one epoch may get skipped due to miner stop
#### System information

Geth version: `v0.3.2`
OS & Version: Windows/Linux/OSX
Commit hash : a40fd5fc86c505e0c1714767f814d1191fcdf601

#### Expected behaviour

We expect the local antimev keystore always has or can sync the latest DKG process.

#### Actual behaviour

But the current implementation may skip specific time point for DKG data synchronization. If the miner worker stops for a while, or the node stops and restarts after a long time, the block synchronization will skip the DKG synchronization execution.

#### Steps to reproduce the behaviour

1. Start up a privnet;
2. Execute `miner.stop()` on one of the CNs;
3. Execute `miner.start()` after several blocks in the next DKG epoch.

#### Backtrace

Here is an example, the log shows the `handleDKG` execution is skipped between block 31 and block 63.

````
INFO [06-11|15:48:42.203] New block in the chain                   "dbft index"=31 "chain index"=31 hash=0x5959ce873667ce74d17fc7f927ce0970d8f236cb77fcf03058e77e28705776c1 "parent hash"=0x83254406a46930faca9a6233c01da5c55bfe0d6b33fd8fd6d5d7b8437a523a1c primary=3 coinbase=0x1212000000000000000000000000000000000003 "mix digest"=0x3e48bc8f2eb502267b1eae6bded2ece31a29829cdf94afb44f37688702643e43
INFO [06-11|15:48:42.203] Fetching latest sealing proposal         "desired number"=32
INFO [06-11|15:48:42.204] DKG task watcher                         currentHeight=31 watchListLength=0
INFO [06-11|15:48:51.300] Imported new chain segment               number=32 hash=331611..317200 blocks=1 txs=0 mgas=0.000  elapsed=87.477ms  mgasps=0.000  snapdiffs=42.42KiB triedirty=244.66KiB
INFO [06-11|15:48:51.549] Imported new chain segment               number=32 hash=c6f05c..bd2cf6 blocks=1 txs=0 mgas=0.000  elapsed=242.959ms mgasps=0.000  snapdiffs=42.42KiB triedirty=244.66KiB
INFO [06-11|15:49:01.527] Imported new chain segment               number=33 hash=68faab..22ace4 blocks=1 txs=0 mgas=0.000  elapsed=82.624ms  mgasps=0.000  snapdiffs=42.42KiB triedirty=244.66KiB
INFO [06-11|15:49:01.866] Imported new chain segment               number=33 hash=07fcc1..719ef5 blocks=1 txs=0 mgas=0.000  elapsed=20.871ms  mgasps=0.000  snapdiffs=42.42KiB triedirty=244.66KiB
INFO [06-11|15:49:01.890] Imported new chain segment               number=33 hash=58f6e0..4b01af blocks=1 txs=0 mgas=0.000  elapsed=21.618ms  mgasps=0.000  snapdiffs=42.42KiB triedirty=244.66KiB
INFO [06-11|15:49:11.750] Imported new chain segment               number=34 hash=40bcd6..401bfa blocks=1 txs=0 mgas=0.000  elapsed=178.225ms mgasps=0.000  snapdiffs=42.42KiB triedirty=244.66KiB
INFO [06-11|15:57:25.149] Legacy pool tip threshold updated        tip=1,000,000,000
INFO [06-11|15:57:25.151] Initializing BFT consensus               account=0x74f4EFFb0B538BAec703346b03B6d9292f53A4CD
INFO [06-11|15:57:25.164] Commit new sealing work                  number=35 sealhash=648089..1ab5a9 "parent hash"=40bcd6..401bfa etherbase=0x1212000000000000000000000000000000000003 txs=0 gas=0          fees=0          elapsed=10.505ms
INFO [06-11|15:57:25.655] New chain segment detected               "dBFT latest block index"=31 "sealing proposal index"=35
INFO [06-11|15:57:25.807] Sealing proposal updated                 number=35 sealhash=648089..1ab5a9 "parent hash"=40bcd6..401bfa txs=0
......
INFO [06-11|15:57:26.248] New block in the chain                   "dbft index"=35 "chain index"=35 hash=0x7063526839368a3a7bd198d74d89c6e0cb9d4af1e49cfbc2e4a9cc2bdb32f862 "parent hash"=0xa411651ade75a88727770ad8e3fb5d766ae6ce339a688821b62e4b53870040c8 primary=0 coinbase=0x1212000000000000000000000000000000000003 "mix digest"=0x95db4e2db1bc954c7ef3bcebba7d9f3569276db7db1bfc6f9b3036bc079c71c9
INFO [06-11|15:57:26.385] Commit new sealing work                  number=36 sealhash=9df5c5..eafb6b "parent hash"=706352..32f862 etherbase=0x1212000000000000000000000000000000000003 txs=0 gas=0          fees=0          elapsed=120.110ms
INFO [06-11|15:57:26.532] Block synchronisation started
INFO [06-11|15:57:26.568] New local node record                    seq=1,749,627,793,395 id=339a00c11f4368fa ip=127.0.0.1 udp=30306 tcp=30306
INFO [06-11|15:57:26.636] Mining aborted due to sync
INFO [06-11|15:57:26.822] Imported new chain segment               number=36 hash=c7dd4d..022dde blocks=1 txs=0 mgas=0.000  elapsed=569.946ms mgasps=0.000  age=8m5s     snapdiffs=42.42KiB triedirty=244.66KiB
INFO [06-11|15:57:27.067] Imported new chain segment               number=37 hash=4ea356..b6040b blocks=1 txs=0 mgas=0.000  elapsed=69.114ms  mgasps=0.000  age=7m56s    snapdiffs=42.42KiB triedirty=244.66KiB
INFO [06-11|15:57:27.922] Imported new chain segment               number=41 hash=4122c8..a846e0 blocks=4 txs=0 mgas=0.000  elapsed=580.951ms mgasps=0.000  age=6m25s    snapdiffs=42.94KiB triedirty=246.57KiB ignored=3
INFO [06-11|15:57:27.968] Fetching latest sealing proposal         "desired number"=36
INFO [06-11|15:57:27.969] Sealing proposal updated                 number=36 sealhash=9df5c5..eafb6b "parent hash"=706352..32f862 txs=0
2025-06-11T15:57:27.987+0800	INFO	initializing dbft	{"height": 36, "view": 0, "index": 2, "role": "Backup"}
2025-06-11T15:57:27.988+0800	DEBUG	reset timer	{"h": 36, "v": 0, "delay": "18.063694174s"}
INFO [06-11|15:57:27.996] Skipping dBFT block callback due to sync "block index"=36 "dbft index"=36
INFO [06-11|15:57:27.996] Skipping dBFT block callback due to sync "block index"=41 "dbft index"=36
2025-06-11T15:57:27.996+0800	DEBUG	received message	{"type": "PrepareResponse", "from": 6, "height": 35, "view": 0, "my_height": 36, "my_view": 0}
INFO [06-11|15:57:27.997] DKG task watcher                         currentHeight=41 watchListLength=0
2025-06-11T15:57:27.997+0800	DEBUG	ignoring old height	{"height": 35}
INFO [06-11|15:57:28.346] New local node record                    seq=1,749,627,793,396 id=339a00c11f4368fa ip=127.0.0.1 udp=30306 tcp=30306
INFO [06-11|15:57:37.549] Imported new chain segment               number=62 hash=aec3c7..1e50c1 blocks=21 txs=12 mgas=34.310 elapsed=6.585s    mgasps=5.210  snapdiffs=148.27KiB triedirty=774.48KiB
INFO [06-11|15:57:37.557] Skipping dBFT block callback due to sync "block index"=62 "dbft index"=36
INFO [06-11|15:57:37.565] New block in the chain                   "dbft index"=36 "chain index"=62 hash=0xaec3c7cd8a426d8e4242ed3f3b811be9d7678e5cd011b5b7af3ce8375f1e50c1 "parent hash"=0x74dd76761e59932c5112e07903909bf40d67cc057a26b87629ea7293568c0519 primary=6 coinbase=0x1212000000000000000000000000000000000003 "mix digest"=0x95db4e2db1bc954c7ef3bcebba7d9f3569276db7db1bfc6f9b3036bc079c71c9
INFO [06-11|15:57:37.594] Commit new sealing work                  number=63 sealhash=dd57cf..23a9fb "parent hash"=aec3c7..1e50c1 etherbase=0x1212000000000000000000000000000000000003 txs=0  gas=0          fees=0          elapsed=29.803ms
INFO [06-11|15:57:37.743] Imported new chain segment               number=63 hash=d511de..7271ee blocks=1  txs=0  mgas=0.000  elapsed=58.395ms  mgasps=0.000  snapdiffs=148.27KiB triedirty=774.48KiB
INFO [06-11|15:57:37.754] Commit new sealing work                  number=64 sealhash=5258be..53103d "parent hash"=d511de..7271ee etherbase=0x1212000000000000000000000000000000000003 txs=0  gas=0          fees=0          elapsed=6.928ms
INFO [06-11|15:57:37.880] Fetching latest sealing proposal         "desired number"=63
INFO [06-11|15:57:37.881] New chain segment detected               "dBFT latest block index"=62 "sealing proposal index"=64
INFO [06-11|15:57:37.880] DKG task watcher                         currentHeight=63 watchListLength=0
INFO [06-11|15:57:38.057] Sealing proposal updated                 number=64 sealhash=5258be..53103d "parent hash"=d511de..7271ee txs=0
INFO [06-11|15:57:38.059] DKG task watcher                         currentHeight=63 watchListLength=0
````

### PR DESCRIPTION
**Pull request by txhsl**
Close #474. Some kind #405 related.

### CODE REVIEW

**Comment by txhsl** [comment]
I've tested the change locally, it works. @songb2 you can try if the node or consensus break in any other case.

File: consensus/dbft/dbft.go [hunk 1]
```diff
@@ -492,9 +492,6 @@ func (c *DBFT) processBlockCb(b dbft.Block[common.Hash]) error {
 				count++
 			}
 		}
-		if !errors.Is(err, antimev.ErrSigAggregation) || count == c.dbft.N() {
-			log.Crit("bug: unexpected error during signature aggregation", "error", err)
-		}
```
Comment (AnnaShaleva) [inline consensus/dbft/dbft.go]: We can't remove it. What if signature aggregation fails due to the fact that some of its parts are invalid (with malicious CNs)?

DKG state should always be in sync with dBFT's current index; otherwise the whole shares validation process is useless. So instead of removing this check we need to make `handleDKG` to update its state according to the current node's state even if some blocks were intentionally skipped by `postBlock`.

Note that this situation also can be reproduced during the node's bootstrap when the node is syncing the long chain for the first time, because `postBlock` callback is not called while Downloader is active:
https://github.com/bane-labs/go-ethereum/blob/a40fd5fc86c505e0c1714767f814d1191fcdf601/consensus/dbft/dbft.go#L2224-L2230

So if DKG can't properly restore its state after such "gaps" in block processing based on the historical DB states, then it's a problem.

Comment (txhsl) [reply consensus/dbft/dbft.go]: > We can't remove it. What if signature aggregation fails due to the fact that some of its parts are invalid (with malicious CNs)?

Then an error is returned. `log.Crit` is aggressive IMO, if there are enough malicious CNs, then other nodes will exit with `os.Exit(1)`?

> DKG state should always be in sync with dBFT's current index; otherwise the whole shares validation process is useless. So instead of removing this check we need to make `handleDKG` to update its state according to the current node's state even if some blocks were intentionally skipped by `postBlock`.

`handleDKG` can deal with the synchronization, with just once execution, as I fixed in this PR. This line is not essential for #474 although.

~~The problem here, is the dBFT is trying to handle cached and fresh consensus payloads with the old global public key, before the node is fully synchronized, or use its old secret key to decrypt transactions.~~ Never mind, it's not happening, reverted.
