### PR TITLE
dbft: refactor shutdown process

### LINKED ISSUE #452: `OnPayload` send on closed channel
#### System information

Geth version: `v0.3.2`
OS & Version: Windows/Linux/OSX

#### Expected behaviour

We always expect the geth code exits without panic.

#### Actual behaviour

@qianhh met a case that dBFT `OnPayload` tried to send a dBFT message on a closed channel from `eth/protocols/dbft`.

#### Steps to reproduce the behaviour

1. He used a wrong antimev keystore to start up a miner node;
2. After `handleDKG` returned an error about the DKG round mismatch, dBFT tried to exit automatically;
3. After dBFT engine exited, a dBFT message came.

#### Backtrace

Sorry, the text has gone, so only a screenshot.

Image

~~@AnnaShaleva It's not a normal use case, so I'm not sure if this should be categorized as a bug, also if we should deal with it inside dBFT or relate it to #405.~~

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Refactor dBFT eventloop and DKG task dispatcher shutdown.

Close #452, a replacement of #461.

### CODE REVIEW

**Comment by AnnaShaleva** [comment]
@txhsl, I see that this PR will conflict with #444 due to the last commit, so we may either finish and merge #444 firstly and then I'll rebase this PR or you may check the last commit and implement its idea in #444 PR. Either way is OK for me, but we should fix the DKG task dispatcher management because right now there's a bug.

@qianhh, @songb2 you're welcomed to review and test.

**Comment by txhsl** [comment]
> Either way is OK for me, but we should fix the DKG task dispatcher management because right now there's a bug.

I prefer that we finish #444 first.

**Comment by AnnaShaleva** [comment]
Ready for review&testing.

**Comment by AnnaShaleva** [comment]
OK, there's one inaccuracy in dispatcher stop process, will fix:
```
INFO [05-27|20:20:13.214] New block in the chain                   "dbft index"=5 "chain index"=5 hash=0x1d777e5beab665dc2ab0d24aba864096535367415eabb4682858b96522fc137a "parent hash"=0x9a2bd21eec6c7e38645451a4337c66008f316d2c0a631e4b744174b85063105b primary=5 coinbase=0x1212000000000000000000000000000000000003 "mix digest"=0x3e48bc8f2eb502267b1eae6bded2ece31a29829cdf94afb44f37688702643e43
INFO [05-27|20:20:13.214] Fetching latest sealing proposal         "desired number"=6
INFO [05-27|20:20:13.214] DKG task dispatcher stopped
panic: send on closed channel

goroutine 4380 [running]:
github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).handleDKG(0xc000798908, 0xc000f33020, 0xc0002a6000, 0xc0126ed908, 0x0, 0x0)
	github.com/ethereum/go-ethereum/consensus/dbft/dkg.go:343 +0x153c
github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).waitForNewSealingProposal(0xc000798908, 0x6, 0x0)
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:2158 +0x4c7
github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).handleChainBlock(0xc000798908, 0xc01293cf08, 0x90?)
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:2491 +0x7d5
github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).eventLoop(0xc000798908)
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:2305 +0xb65
created by github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).Start in goroutine 4373
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:2093 +0x5a9
```

**Comment by AnnaShaleva** [comment]
Fixed, ready for review.

File: consensus/dbft/dbft.go [hunk 1]
```diff
@@ -2494,7 +2474,6 @@ func (c *DBFT) handleChainBlock(h *types.Header, checkForSync bool) error {
 			"block index", h.Number.Int64(),
 			"dbft index", c.dbft.BlockIndex,
 		)
-		return nil
```
Comment (txhsl) [inline consensus/dbft/dbft.go:2512]: This makes it no longer a short path here.

If we are sure that the following codes will not be triggered anyway, then it's OK, but I think they will.

Fixed, but leave this for comments, maybe I'm wrong.

File: consensus/dbft/dkg.go [hunk 2]
```diff
@@ -340,275 +340,315 @@ func (c *DBFT) handleDKG(snapshot *snapshot, keystore *antimev.KeyStore, h *type
...
-			select {
-			case c.executeProofTaskChan <- &taskList:
-			default:
-				// Give up the tasks since the channel is going to block DKG and dBFT.
-				return fmt.Errorf("proof task channel is full")
-			}
+		select {
+		case <-c.quit:
+			return nil
+		case c.dkgTaskExecutorCh <- &taskList: // send even if taskList is empty since dkgTaskExecutorCh needs a heartbeat.
```
Comment (txhsl) [inline consensus/dbft/dkg.go]: Also related to the line https://github.com/bane-labs/go-ethereum/pull/467/files#diff-c80584fa2bebbf3162e0d5141bf4b091712fdba0776be26333fe2a0f72249f7eR556, I think we need the heartbeat sent from `handleDKG()` instead of inside `dkgTaskExecutor()`.

This is because `dkgTaskExecutor()` maybe time-consuming, but we require the `dkgTaskWatcher()` to be executed once per new height. So this change will delay the regular loop of `retryList` check.

It looks OK before we enable ZK generation, but after that, the `dkgTaskExecutor()` will become busy and empty `taskList` will be stuck in the `dkgTaskExecutorCh` and trigger the `proof task channel is full` error.

```
CRIT [06-03|11:36:29.401] Failed to fetch latest sealing proposal  index=12 err="failed to initialize DKG snapshot at height 11: proof task channel is full"
```

Update: Also encountered a `send on closed channel` panic, I'm going to refactor this part.

File: consensus/dbft/dkg.go [hunk 3]
```diff
@@ -340,275 +340,315 @@ func (c *DBFT) handleDKG(snapshot *snapshot, keystore *antimev.KeyStore, h *type
...
-			default:
-				panic(fmt.Errorf("unknown DKG method to prove: %s", task.Method))
+				// Release the cache when the task list is fully handled.
+				sevenMsgR1CS = nil
+				sevenMsgPK = nil
+			}
+			select {
+			case <-c.quit:
+				break executeLoop
+			case c.dkgTaskWatcherCh <- watchList: // send even if taskList is empty since dkgTaskWatcherCh needs a heartbeat.
```
Comment (txhsl) [inline consensus/dbft/dkg.go]: As I've mentioned above, this may be blocked by the ZK proof generation.

**Review by txhsl — CHANGES_REQUESTED** [review]

File: consensus/dbft/dkg.go [hunk 4]
```diff
@@ -340,275 +340,315 @@ func (c *DBFT) handleDKG(snapshot *snapshot, keystore *antimev.KeyStore, h *type
...
-							log.Error("DKG get transaction receipt status error", "txHash", item.TxHash, "status", receipt["status"])
+
+						// Send successfully, wait 3 blocks to check transaction status.
+						if item.TxHash != nil && currentHeight-item.SendHeight == 3 {
+							receipt, err := c.txAPI.GetTransactionReceipt(context.Background(), *item.TxHash)
+							if err != nil {
+								needRetry = true
+								log.Error("DKG get transaction receipt failed", "err", err, "txHash", item.TxHash)
+							}
+							if receipt["status"] != types.ReceiptStatusSuccessful {
```
Comment (qianhh) [inline consensus/dbft/dkg.go]: If the call to `GetTransactionReceipt()` fails and returns an error, then the `receipt` variable will be nil. Attempting to access it directly will cause a panic.

```suggestion
							} else if receipt["status"] != types.ReceiptStatusSuccessful {
```

Comment (txhsl) [reply consensus/dbft/dkg.go]: Seems like an issue not related to this PR but the original #332, we may open another PR to fix this.

But the fix is simple, yes, we can commit your suggestion now as well.

Comment (qianhh) [reply consensus/dbft/dkg.go]: Yes, I just happened to see this code and noticed a minor issue here. So I commented on it right there.

**Comment by txhsl** [comment]
Rebased to the main branch, otherwise may encounter static pool errors in testing.

File: consensus/dbft/dbft.go (hunk 1 above)
Comment (AnnaShaleva) [reply consensus/dbft/dbft.go:2512]: Good catch, this change was added accidentally. The fix should be a part of this commit, otherwise this commit is illegal. So I moved this fix to this commit, will push an update soon.

File: consensus/dbft/dbft.go [hunk 5]
```diff
@@ -238,9 +238,10 @@ type DBFT struct {
 	fakeDiff bool // Skip difficulty verifications
 
 	// The fields for dkg
-	dkgSnapshot       *snapshot
-	dkgTaskExecutorCh chan *taskList
-	dkgTaskWatcherCh  chan *taskList
+	dkgSnapshot        *snapshot
+	dkgTaskExecutorCh  chan *taskList
+	dkgTaskWatcherCh   chan *taskList
+	dkgWatcherLooperCh chan struct{}
```
Comment (AnnaShaleva) [inline consensus/dbft/dbft.go]: And this new channel is useless and may be avoided even if we'd like to send heartbit irrespective from tasks processing.  Will push an update in a few hours.

File: consensus/dbft/dkg.go [hunk 6]
```diff
@@ -340,275 +340,332 @@ func (c *DBFT) handleDKG(snapshot *snapshot, keystore *antimev.KeyStore, h *type
...
+		select {
+		case <-c.quit:
+			return nil
+		case c.dkgTaskWatcherCh <- nil:
+		default:
+			// Use non-blocking send since if dkgTaskWatcherCh is busy with processing
+			// some other tasks, then triggering it one more time is completely useless.
+			log.Info("failed to send heartbit signal to DKG task watcher: handler is busy, will retry after the next block",
+				"index", h.Number.Uint64())
+		}
```
Comment (AnnaShaleva) [inline consensus/dbft/dkg.go:364]: This part replaces `dkgWatcherLooperCh`.

File: consensus/dbft/dkg.go [hunk 7]
```diff
@@ -340,275 +340,332 @@ func (c *DBFT) handleDKG(snapshot *snapshot, keystore *antimev.KeyStore, h *type
...
+			sevenMsgPK = nil
+
+			if len(watchList) > 0 {
+				select {
+				case <-c.quit:
+					break executeLoop
+				case c.dkgTaskWatcherCh <- &watchList:
+					// Blocking send since transactions have been constructed and sent, we need to
+					// notify dkgTaskWatcherCh anyway even if it will block dBFT operation.
 				}
```
Comment (AnnaShaleva) [inline consensus/dbft/dkg.go]: @txhsl pay attention to this part since the behaviour was different in your commit. I think it's important to wait until `dkgTaskWatcherCh` will pick up this new watchlist because the transactions were sent to the network, so we need to track their status anyway. So it's a valid reason to block even standard dBFT flow.

Also, one iteration of `dkgTaskWatcherCh` handler doesn't take a lot of time since this handler just tries to resend existing tasks. So we shouldn't spend an eternity in `case c.dkgTaskWatcherCh <- &watchList:`.

File: consensus/dbft/dbft.go (hunk 5 above)
Comment (AnnaShaleva) [reply consensus/dbft/dbft.go]: Updated, see the reviewcomment.

File: consensus/dbft/dkg.go [hunk 8]
```diff
@@ -340,275 +340,331 @@ func (c *DBFT) handleDKG(snapshot *snapshot, keystore *antimev.KeyStore, h *type
 		if err := keystore.Persist(); err != nil {
 			return fmt.Errorf("failed to persist keystore, err: %v", err)
 		}
+		// Notify dkgTaskExecutorCh iff there's new task.
 		if len(taskList) > 0 {
 			select {
-			case c.executeProofTaskChan <- &taskList:
+			case <-c.quit:
```
Comment (txhsl) [inline consensus/dbft/dkg.go:346]: I have a question about the usage of `select` here and several places else, outside `for {}` blocks.

AFAIK, if both of the two cases are executable, then Golang will randomly pick one of them.

I've encountered `send on closed channel` in the first implementation. Is it really safe to use as this?

File: consensus/dbft/dkg.go (hunk 6 above)
Comment (txhsl) [reply consensus/dbft/dkg.go:364]: The `dkgTaskWatcherCh` won't be that busy, so this will make the watcher to run one more time than once per block, at several specific time points.

But if you insist that we shouldn't have one more channel to handle the heartbeats, I'm OK with it.

File: consensus/dbft/dkg.go [hunk 9]
```diff
@@ -340,275 +340,331 @@ func (c *DBFT) handleDKG(snapshot *snapshot, keystore *antimev.KeyStore, h *type
...
-					log.Error("Unsupported ZK version", "version", task.ZKVersion)
-					continue
+					panic(fmt.Errorf("unknown DKG method to prove: %s", task.Method))
+				}
+			}
+			// Release the cache when the task list is fully handled.
+			sevenMsgR1CS = nil
+			sevenMsgPK = nil
+
+			if len(watchList) > 0 {
```
Comment (txhsl) [inline consensus/dbft/dkg.go]: IMO, the `watchList` won't be `nil` here, so I prefer to remove the check.

File: consensus/dbft/dkg.go (hunk 7 above)
Comment (txhsl) [reply consensus/dbft/dkg.go]: OK then, I see your concern. But I'm worrying about the usage of `select`, which makes the blocking here dangerous, ref https://github.com/bane-labs/go-ethereum/pull/467#discussion_r2140673705.

File: consensus/dbft/dkg.go (hunk 9 above)
Comment (AnnaShaleva) [reply consensus/dbft/dkg.go]: Agree, fixed.

File: consensus/dbft/dkg.go (hunk 8 above)
Comment (AnnaShaleva) [reply consensus/dbft/dkg.go:346]: It's a valid question.

> AFAIK, if both of the two cases are executable, then Golang will randomly pick one of them.

That's true, except the default case. Default is executed only when no other options are available.

> I've encountered send on closed channel in the first implementation.

It happens due to the fact that `dkgTaskWatcherCh` may be closed in the end of `dkgTaskWatcher` earlier than subsequent `handleDKG` call finishes its execution. So technically, there was a race between `handleDKG` sending to `dkgTaskWatcherCh` and `dkgTaskWatcher` closing `dkgTaskWatcherCh`. It's a bug, and it should be solved by proper awaiting of all routines completion before closing `dkgTaskWatcherCh`. The same is relevant for `dkgTaskExecutorCh`.

Updated, but we need to test the updated version.

File: consensus/dbft/dkg.go (hunk 7 above)
Comment (AnnaShaleva) [reply consensus/dbft/dkg.go]: For this case proper awaiting of eventLoop before closing `dkgTaskWatcherCh` should also solve the problem, see the updated version.

File: consensus/dbft/dkg.go (hunk 8 above)
Comment (txhsl) [reply consensus/dbft/dkg.go:346]: I see the difference, will have a detailed check tomorrow.

**Review by txhsl — APPROVED** [review]
