### PR TITLE
dbft: fix dbft api for Geth JavaScript console. 

### LINKED ISSUE #36: DBFT module error
cannot call dbft functions
image

### PR DESCRIPTION
**Pull request by chenquanyu**
Close #36 DBFT module error. This issue is caused by the command in `"JavaScript console` needs to be added in `web3ext`.

### CODE REVIEW

**Review by nicolegys — APPROVED** [review]

File: internal/web3ext/web3ext.go [hunk 1]
```diff
@@ -90,6 +91,51 @@ web3._extend({
...
+		}),
+		new web3._extend.Method({
+			name: 'status',
+			call: 'dbft_status',
+			params: 1
+		}),
+		new web3._extend.Method({
+			name: 'getPrimary',
+			call: 'dbft_getPrimary',
+			params: 1,
```
Comment (AnnaShaleva) [inline internal/web3ext/web3ext.go:129]: We have `inputFormatter: [null]` for the analogue Clique method and it seems to me like a good practice. Don't we need to set the same one for `getPrimary` and `getCoinbase`?

**Review by AnnaShaleva — COMMENTED** [review]
Could you also please, add `Close #36.` message to the PR description? It's needed for proper GitHub "Development" section links displaying.

File: internal/web3ext/web3ext.go (hunk 1 above)
Comment (chenquanyu) [reply internal/web3ext/web3ext.go:129]: This `inputFormatter: [null]` seems to disable the check for params count, so I think we only need this for `dbft_status`.

**Comment by nicolegys** [comment]
now `dbft.status` can be called without param

File: internal/web3ext/web3ext.go (hunk 1 above)
Comment (nicolegys) [reply internal/web3ext/web3ext.go:129]: I think `getPrimary` and `getCoinbase` also need this because they can be called without param in the code implementation.

Comment (chenquanyu) [reply internal/web3ext/web3ext.go:129]: > I think `getPrimary` and `getCoinbase` also need this because they can be called without param in the code implementation.

I have tried to add it for `getPrimary` and `getCoinbase`, but call them without param will cause exception. 

image

Comment (nicolegys) [reply internal/web3ext/web3ext.go:129]: Oh sorry, my bad. I mean to say `getSigners` and `getValidators` can be called without param, and they actually work well. It's OK OK.

**Review by AnnaShaleva — APPROVED** [review]
